CREATE SCHEMA IF NOT EXISTS "PUBLIC";
CREATE USER IF NOT EXISTS yo PASSWORD 'yo';
ALTER USER yo ADMIN TRUE;
GRANT ALL TO yo;

drop table attache_file if exists;
drop table member if exists;
drop table member_authorities if exists;

create table attache_file (id bigint generated by default as identity, content_type varchar(255), file_id varchar(255), name varchar(255) not null, path varchar(255), size bigint, created_date TIMESTAMP, primary key (id));
create table member (id bigint generated by default as identity, cell_phone_number varchar(100), in_phone_number varchar(100), created_date timestamp, department_nm varchar(100), email varchar(100),  grade_nm varchar(100), charge_room varchar(100), last_modified_date timestamp, name varchar(50) not null, nick_name varchar(50), note clob, password varchar(100) not null, signin_id varchar(50) not null, status varchar(255), created_by_id bigint, last_modified_by_id bigint, profile_image_id bigint, primary key (id));
create table member_authorities (member_id bigint not null, authority varchar(255));
CREATE TABLE HOLYDAY ( ID bigint generated by default as identity, YEAR INTEGER, TITLE VARCHAR(100), DATE VARCHAR(20), TYPE VARCHAR(20), CONSTRAINT HOLYDAY_ID_IDX PRIMARY KEY (ID) ) ;

CREATE
	TABLE
		VOLUNTEER_LOG(
			ID BIGINT GENERATED BY DEFAULT AS IDENTITY,
			w_Date TIMESTAMP,
			p_Year VARCHAR(4),  
			p_Date VARCHAR(10), 
			user_youth_boy_volunteer INTEGER,
			user_youth_girl_volunteer INTEGER,
			user_man_volunteer INTEGER,
			user_woman_volunteer INTEGER,
			Etc_Inform varchar(1000),
	created_by_id BIGINT,
	last_modified_by_id BIGINT,
	created_date TIMESTAMP,
	last_modified_date TIMESTAMP,
	CONSTRAINT VOLUNTEER_LOG_ID_IDX PRIMARY KEY(ID)
);

create table member_menu (id bigint generated by default as identity, create_yn tinyint(1) default 0, created_date timestamp, last_modified_date timestamp, menu_id bigint not null, print_yn tinyint(1) default 0, read_yn tinyint(1) default 0, update_yn tinyint(1) default 0, member_id bigint, primary key (id));
create table menu_item (id bigint generated by default as identity, created_date timestamp, last_modified_date timestamp, menu_name varchar(255), path varchar(255), sub_menu_name varchar(255), primary key (id));
create index idx_member_menu_menu_id on member_menu (menu_id);
create index idx_member_menu_created_date on member_menu (created_date);
alter table member_menu add constraint FKl4uiy1plnwgmwsawid4u631qr foreign key (member_id) references member;


-- member: admin/admin
INSERT INTO MEMBER(id, signin_id, password, name, nick_name, email, status,  department_nm, cell_phone_number) 
VALUES(1, 'admin', '662740c0b7af6d81b10126ba8bcf82b0db8efccf58533d0b7ae383bb71668ea14f67721481ebf711', '시스템 관리자', '시스템 관리자', 'system@softfun.io', 'ACTIVE',  'DI', '01028447678');
INSERT INTO MEMBER(id, signin_id, password, name, nick_name, email, status,  department_nm, cell_phone_number, grade_nm, charge_room)
VALUES(11, 'user01', '785636a20b3865cd0b630eb255d156aebfde5980748c9bd5062debe29abb04890a9656692dbdc2e3', '사용자', 'Leader', 'robin@softfun.io', 'ACTIVE',  '', '01012341234', 'Leader', '');

INSERT INTO MEMBER_AUTHORITIES(member_id, authority) VALUES(1, 'ADMINISTRATOR');
INSERT INTO MEMBER_AUTHORITIES(member_id, authority) VALUES(11, 'MANAGER');

insert into menu_item(id, menu_name, sub_menu_name, path, created_date) values(4, '자료실', '자원봉사', '/dataroom/volunteerLog', now());
insert into menu_item(id, menu_name, sub_menu_name, path, created_date) values(22, '관리자', '회원관리', '/settings/members', now());
insert into menu_item(id, menu_name, sub_menu_name, path, created_date) values(23, '관리자', '휴관일관리', '/settings/holyday', now());

insert into member_menu(id, read_yn, print_yn, create_yn, update_yn, menu_id, member_id, created_date) values (1, 1, 1, 1, 1, 4, 1, now());
insert into member_menu(id, read_yn, print_yn, create_yn, update_yn, menu_id, member_id, created_date) values (2, 1, 1, 1, 1, 22, 1, now());
insert into member_menu(id, read_yn, print_yn, create_yn, update_yn, menu_id, member_id, created_date) values (3, 1, 1, 1, 1, 23, 1, now());




